# Generated by Django 5.2.1 on 2025-05-28 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="documents/")),
                ("file_type", models.CharField(max_length=50)),
                ("size", models.IntegerField()),
                ("pages", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                (
                    "processing_status",
                    models.CharField(default="pending", max_length=50),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("ai_response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("source_chunks", models.JSONField(default=list)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docapp.chatsession",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatsession",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="docapp.document"
            ),
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("text", models.TextField()),
                ("page_number", models.IntegerField()),
                ("start_char", models.IntegerField(blank=True, null=True)),
                ("end_char", models.IntegerField(blank=True, null=True)),
                ("chunk_type", models.CharField(default="semantic", max_length=50)),
                ("embedding_id", models.CharField(max_length=255)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docapp.document",
                    ),
                ),
            ],
        ),
    ]
